/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JupyterLab command to execute
 */
export type Command = string;
/**
 * List of steps to execute before starting the benchmark/analysis
 */
export type Setup = Step[];
/**
 * List of steps to analyse in scenario
 */
export type Run = Step[];
/**
 * List of steps to execute after finishing the benchmark/analysis
 */
export type Cleanup = Step[];

export interface CustomScenarioOptions {
  setup?: Setup;
  run: Run;
  cleanup?: Cleanup;
  [k: string]: any;
}
/**
 * Command to execute
 */
export interface Step {
  command?: Command;
  arguments?: Arguments;
  [k: string]: any;
}
/**
 * JupyterLab command arguments
 */
export interface Arguments {
  [k: string]: any;
}
